server:
  port: ${PORT:9090}
  servlet:
    context-path: /
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 250000
      idle-timeout: 30000
      minimum-idle: 0
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 12MB
app:
  admin:
    key: ${ADMIN_KEY:lucky8839}
    phone: ${ADMIN_PHONE:9926361994}
    password: ${ADMIN_PASSWORD:lucky8839}
  upload-dir: ${UPLOAD_DIR:${user.dir}/uploads}